AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket configured for hosting the cloudformation templates in aws
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create
    Default: "load-test-us-east-1-public-cloudformation-templates"
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
          Status: Enabled
        - NoncurrentVersionExpirationInDays: 3
          Status: Enabled
      BucketName: !Ref 'BucketName'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    DeletionPolicy: Delete